# Generated by Django 3.0 on 2022-03-24 20:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Site ID')),
                ('name', models.CharField(max_length=255)),
                ('mod_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation', models.IntegerField(blank=True, max_length=4, null=True)),
                ('batlas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Barrington Atlas')),
                ('pleiades_url', models.URLField(blank=True, null=True)),
                ('perseus_url', models.URLField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph', tinymce.models.HTMLField(blank=True, null=True)),
                ('natural_marker', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('marker_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Marker ID')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Koina',
            fields=[
                ('koina_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Koina ID')),
                ('member_count', models.IntegerField(blank=True, max_length=4, null=True)),
                ('activities', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Inscription')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Koina',
            },
        ),
        migrations.CreateModel(
            name='Ancient_Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, help_text='Text and section', max_length=255, null=True)),
                ('author_date', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('citation_url', models.URLField(blank=True, null=True)),
                ('bibliographic_reference', models.CharField(blank=True, help_text="Sources without available URL's", max_length=255, null=True)),
                ('cityname', models.ForeignKey(blank=True, db_column='name', on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Ancient Source',
                'verbose_name_plural': 'Ancient Sources',
            },
        ),
    ]
