# Generated by Django 3.0 on 2022-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, choices=[('Apollonius of Rhodes', 'Apollonius of Rhodes'), ('[Orpheus]', '[Orpheus]'), ('Valerius Flaccus', 'Valerius Flaccus')], max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Places_Referenced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('ritual', models.CharField(blank=True, max_length=255, null=True)),
                ('ritual_deity', models.CharField(blank=True, max_length=255, null=True)),
                ('argonautica_edition', models.CharField(blank=True, choices=[('Apollonius of Rhodes', 'Apollonius of Rhodes'), ('[Orpheus]', '[Orpheus]'), ('Valerius Flaccus', 'Valerius Flaccus')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Place Referenced',
                'verbose_name_plural': 'Places Referenced',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_stop', models.CharField(blank=True, choices=[('direct', 'direct'), ('indirect', 'indirect')], max_length=255, null=True)),
                ('line_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ritual', models.CharField(blank=True, max_length=255, null=True)),
                ('ritual_deity', models.CharField(blank=True, max_length=255, null=True)),
                ('argonautica_edition', models.CharField(blank=True, choices=[('Apollonius of Rhodes', 'Apollonius of Rhodes'), ('[Orpheus]', '[Orpheus]'), ('Valerius Flaccus', 'Valerius Flaccus')], max_length=255, null=True)),
                ('crew', models.ManyToManyField(blank=True, help_text='People on the Ship Manifest at the time', null=True, related_name='crew', to='argonautica.Person')),
            ],
            options={
                'verbose_name': 'Sequence Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['line_number'],
            },
        ),
    ]
