# Generated by Django 3.0 on 2022-03-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('argonautica', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='next_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='stops',
            name='place_of_stop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='stops',
            name='previous_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='stops',
            name='ritual_people',
            field=models.ManyToManyField(blank=True, help_text='People associated with the ritual', null=True, related_name='ritualpeople', to='argonautica.Person'),
        ),
        migrations.AddField(
            model_name='places_referenced',
            name='next_place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='next2', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='places_referenced',
            name='place_referenced',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='places_referenced',
            name='previous_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous2', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='places_referenced',
            name='referenced_by',
            field=models.ForeignKey(blank=True, help_text='Person making the place reference', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking', to='argonautica.Person'),
        ),
        migrations.AddField(
            model_name='places_referenced',
            name='ritual_people',
            field=models.ManyToManyField(blank=True, help_text='People associated with the ritual', null=True, related_name='ritualpeople2', to='argonautica.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
