# Generated by Django 3.0 on 2022-03-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(blank=True, null=True)),
                ('inscription', models.CharField(blank=True, max_length=255, null=True)),
                ('inscription_text', models.TextField(blank=True, null=True)),
                ('bibliographic', models.CharField(blank=True, help_text='List Mack pages.', max_length=255, null=True)),
                ('date_range', models.CharField(blank=True, max_length=255, null=True)),
                ('date_begin', models.IntegerField(blank=True, null=True)),
                ('date_end', models.IntegerField(blank=True, null=True)),
                ('inscriptionlink', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('inscription_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Inscription ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('alt_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.IntegerField(blank=True, max_length=4, null=True)),
                ('end_date', models.IntegerField(blank=True, max_length=4, null=True)),
                ('date_info', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='inscriptions')),
                ('inscription_text', models.TextField(blank=True)),
                ('bibliography', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('dating_certainty', models.TextField(blank=True)),
                ('start_date_CE', models.IntegerField(blank=True, max_length=4, null=True)),
                ('end_date_CE', models.IntegerField(blank=True, max_length=4, null=True)),
            ],
            options={
                'ordering': ['inscription_id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Inscription')),
            ],
        ),
    ]
