# Generated by Django 3.0 on 2022-03-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='find_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='sites_mentioned',
            field=models.ManyToManyField(blank=True, null=True, related_name='sites_mentioned', through='inscriptions.ReferenceSite', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='grant',
            name='granting_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granting', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='grant',
            name='receiving_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to='sites.Site'),
        ),
    ]
