# Generated by Django 3.0 on 2022-03-24 20:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0002_auto_20220324_1647'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('individual_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Individual ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('patronym', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Inscription')),
                ('site', models.ForeignKey(blank=True, help_text="The individual's city of origin", null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('site_origin', models.ForeignKey(blank=True, help_text="Inscription's city - can be left blank as long as the inscription is selected.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_origin', to='sites.Site')),
            ],
            options={
                'ordering': ['name', 'patronym'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Role ID')),
                ('title', models.CharField(max_length=255)),
                ('certainty', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Enter a value between 0 and 1.', max_digits=3, verbose_name='certainty')),
                ('comments', models.TextField(blank=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Individual')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Priesthood',
            fields=[
                ('priesthood_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Priesthood ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('deity_id', models.CharField(blank=True, max_length=10)),
                ('deity', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('att_honor', models.CharField(blank=True, max_length=255)),
                ('cer_ritual', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('inscription', models.ManyToManyField(blank=True, to='inscriptions.Inscription')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Role')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
